### ISSUE TITLE
неверное поведение при разложении производной на множители

### ISSUE THREAD

**Issue by colt-browning** [RuRo/pyRoPE#1]
![image](https://cloud.githubusercontent.com/assets/9993953/6004527/7c69281a-ab14-11e4-8614-dbc5a441dd00.png)
То ли здесь случайно потерян множитель, то ли имеется в виду, что всё равно, что приравнивать к нулю — 2(_x_–1) или _x_–1, но и в этом случае не следует писать, что сначала _f'_ равно чему-то одному, а потом чему-то другому.

**Comment by RuRo** [comment]
Будет ли лучше, если я изменю это на
Working with the derivative function:
f' = 2x-2
Finding roots of 2x-2
2x-2 = 0
Factoring out 2
x - 1 = 0
Finding roots of x-1
Found roots are: 1

**Comment by colt-browning** [comment]
Несомненно. В этом случае не будет никаких претензий по этому вопросу.
